// which type of branch change is determined by comparator and the branch offset is determined by imm_gen
//this computes the target address
module branch_target_adder(
    input[31:0] pc_current,
    input[31:0] branch_imm,//offset generated by imm_gen
    output[31:0] branch_target
);
assign branch_target=pc_current+branch_imm;

endmodule